#!/bin/bash

#SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"


# ==================== CONFIGURATION ====================
if [ -f "$SCRIPT_DIR/config.local.sh" ]; then
    source "$SCRIPT_DIR/config.local.sh"
else
    echo "❌ ERROR: config.local.sh not found"
    echo ""
    echo "Please run the installer first:"
    echo "  cd $SCRIPT_DIR"
    echo "  bash install.sh"
    exit 1
fi


source $SCRIPT_DIR/lib/init.sh "$@" || exit 1

# ==================== CREATE FOLDERS ====================
mkdir -p $PROJECT_PATH
mkdir -p $PROJECT_PATH/src
echo "✓ Project folders created"

# ==================== CREATE PYTHON VIRTUAL ENVIRONMENT =======
source $SCRIPT_DIR/lib/venv_setup.sh

# ==================== CREATE ROS ENV ALIAS SCRIPT ====================
source $SCRIPT_DIR/lib/alias_setup.sh





# ==================== BUILD ====================
cd $PROJECT_PATH
colcon build
echo "✓ Workspace built"

# ==================== CREATE ROS PACKAGE ====================
source $SCRIPT_DIR/lib/pkg_setup.sh





# ==================== ADD TEMPLATES ====================
source $SCRIPT_DIR/lib/template_setup.sh

# ==================== GIT SETUP ====================================
source $SCRIPT_DIR/lib/git_setup.sh


# ==================== FINAL STEPS ====================
echo ""
echo "✅ Project setup complete!"
echo "Next steps:"
echo "  1. source ~/.bashrc"
echo "  2. $PROJECT_NAME"
